version: '3.9'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es
    environment:
#      - node.name=es
#      - cluster.name=es-docker-cluster
    #   - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
#    networks:
#      - esnet
#  elasticsearch:
#    image: elasticsearch:5.6
#    container_name: food_elasticity_elasticsearch
#    environment:
#      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
#    volumes:
#      - esdata1:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200


volumes:
  esdata:
    driver: local
#  data02:
#    driver: local
#  data03:
#    driver: local

#networks:
#  esnet:
#    driver: bridge
